icons_format = "{icon}"

[theme]
theme = "/home/cashpw/proj/i3status-rust/files/themes/tomorrow-night.toml"

[theme.overrides]
separator = ""

[icons]
icons = "material-nf"
[icons.overrides]

[[block]]
block = "packages"
package_manager = ["dnf"]
interval = 1800
format = " $icon $dnf.eng(w:1) updates available "
format_singular = " $icon One update available "
format_up_to_date = ""
[[block.click]]
# shows dmenu with cached available updates. Any dmenu alternative should also work.
button = "left"
cmd = "dnf list -q --upgrades | tail -n +2 | rofi -dmenu"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
interval = 60
warning = 80.0
alert = 90.0
format = " $path $percentage "
format_alt = " $path $percentage $used.eng(w:0)/$total.eng(w:0) "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
#format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "temperature"
format = " $average "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10

[[block]]
block = "music"
format = "{ $icon $combo.str(max_w:40,rot_interval:0.5) $play |}"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
# Warning is used when muted
warning_fg = "#c5c8c6" # idle_fg
warning_bg = "#373b41" # idle_bg
# Idle is used when unmuted
idle_bg = "#81a2be" # Blue
idle_fg = "#1d1f21" # Background

[[block]]
block = "bluetooth"
mac = "74:74:46:26:4C:6F"
format = " $icon{ $percentage|} "
disconnected_format = " $icon "
[[block.click]]
button = "left"
cmd = "bluetoothctl connect 74:74:46:26:4C:6F"
[[block.click]]
button = "right"
cmd = "bluetoothctl disconnect 74:74:46:26:4C:6F"

[[block]]
block = "bluetooth"
mac = "C3:FD:60:D2:CE:74"
format = " 󰍽{ $percentage|} "
disconnected_format = " $icon "
[[block.click]]
button = "left"
cmd = "bluetoothctl connect C3:FD:60:D2:CE:74"
[[block.click]]
button = "right"
cmd = "bluetoothctl disconnect C3:FD:60:D2:CE:74"

[[block]]
block = "net"
format = " $icon{ $ssid|} "
format_alt = " $icon ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) {$signal_strength $ssid|Wired connection} $ip $ipv6 "

[[block]]
block = "weather"
autolocate = true
autolocate_interval = "once"
format = " $icon $weather $temp "
format_alt = " {($location $icon_ffin $weather_verbose_ffin $temp_favg.eng(w:0), {$temp_fmin.eng(w:0)}-{$temp_fmax.eng(w:0)}, {$wind_fmin.eng(w:0)}-{$wind_fmax.eng(w:0)} m/s $direction_ffin, up $sunrise.datetime(f:'%R') down $sunset.datetime(f:'%R')|Forecast unavailable} "
[block.service]
name = "nws"
units = "imperial"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 1
format = " 󰃭 $timestamp.datetime(f:'%m-%d %H:%M:%S') "
